### ISSUE TITLE
我将token检验配置成了Filter，全局校验token，成功的时候同样放到request中

### ISSUE THREAD

**Issue by bestK** [hyrijk/spring-boot-blog#1]
但是为什么这个时候使用 @CurrentUser注解就不能获得当前用户了？ 自己调试的时候发现。只要没加 @LoginRequire   的话 ，@CurrentUser这个注解就不会执行，这是为什么？请教下，谢谢！

**Comment by hyrijk** [comment]
我的代码里面是[检测到了`@LoginRequired`](https://github.com/hyrijk/spring-boot-blog/blob/9148230546acded39ed930cef8eeb305e11f663e/src/main/java/com/hpm/blog/config/AuthenticationInterceptor.java#L38)这个注解，才会执行 `request.setAttribute("currentUser", user);
`

**Comment by bestK** [comment]
明白了，谢谢！
