### ISSUE TITLE
创建post表的时候报错。。

### ISSUE THREAD

**Issue by enjoyCoding666** [hyrijk/spring-boot-blog#2]
Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
意思是只有一个TIMESTAMP 列能设置为DEFAULT 或ON UPDATE。。
好像是mysql版本不一样造成的。

**Comment by hyrijk** [comment]
久版本的MySQL不行，5.6之后的版本可以
