### ISSUE TITLE
关于实现用户注册接口文章

### ISSUE THREAD

**Issue by immarktube** [hyrijk/spring-boot-blog#3]
您好，不知您是否还维护此项目
     在阅读您的实现用户注册接口这篇文章，发现了几个问题，我的代码中在UserService里` @Autowired
    public UserService(UserMapper userMapper) {
        this.userMapper = userMapper;
    }`这段代码的参数userMapper会出现Could not autowire. No beans of 'UserMapper' type found这个问题。
还有，在我打开SpringBootBlogApplication.java, 添加mybatis扫描注解时也会发生错误，Cannot resolve symbol 'MapperScan'。希望能得到您及时的回复！

**Comment by littleSkylark** [comment]
没有mapperScan 是因为你没有引入mybatis的包（或缺少），配置mapperScan后IDE还会提示no bean，不用管（IDE不识别mapperScan）
